### PR TITLE
Add C++11's 'using' syntax

### PR DESCRIPTION
**Pull request by vkontrimas**
I realise this isn't meant to be an exhaustive list but I am fond of C++11's `using typeName = returnType (parameterTypes)` syntax. I think it's a valuable addition. Hopefully there aren't pitfalls I'm not aware off!

image

### CODE REVIEW

**Comment by jerryryle** [comment]
Thanks for the contribution! This site is currently C-specific and I'm not sure I want to tackle C++ yet, if ever. C++ offers alternatives to classical function pointers (such as lambdas, std::function/std::bind) and I don't want this site to accidentally endorse a specific pattern by documenting only that pattern. That said, I'm open to alternative viewpoints and a discussion.

**Comment by vkontrimas** [comment]
In the past I've ended up referring to this page when writing C++ and I'm probably not the only such person. So I feel like including `using` would be helpful. In fact I opened this pull request because I wanted to double check the syntax after not touching C++ for a while.

That being said, you're totally right about this inviting alternatives beyond classical function pointers. Only a matter of time until someone suggests adding `std::function` too 😀.

It's totally fair if you just want to keep this in C!

**Comment by jerryryle** [comment]
Okay. Sounds fair. I'll merge, but then probably tweak it a bit to point out that there are alternatives in C++.

**Comment by jerryryle** [comment]
Merged and tweaked. Thank you again for the contribution with the example code!

**Pull request merged**
